### PR TITLE
Update timeout in docs

### PR DESCRIPTION
**Pull request by broldak**
Timeout of 30 does not work. Tested with clean checkout and 60 works fine.

### CODE REVIEW

**Comment by broldak** [comment]
Issue #51.

**Comment by broldak** [comment]
@worr Wanted to get your feedback on this.

**Comment by worr** [comment]
Thanks for the PR! Can you actually fix this in the README, which typedoc is pulling in?

**Comment by worr** [comment]
Closed from lack of response.

**Pull request closed without merging**
