### PR TITLE
BUGFIX fix season numbers for Episodes

### PR DESCRIPTION
**Pull request by js-kyle**

### CODE REVIEW

**Comment by js-kyle** [comment]
@worr Would there be any change of a merge & npm publish for this one? Thank you

**Comment by worr** [comment]
@js-kyle Sorry, been a rough few weeks here for me.

You have a build failure from not including the radix in the call to `parseInt`. I'd also like a test with an invalid number (since the api I use can sometimes return invalid data).

https://travis-ci.org/github/worr/node-imdb-api/jobs/676757957

**Comment by js-kyle** [comment]
No problem, hope things work out.

I'll take a look at those things - sorry, didn't even check the build for the PR

**Comment by worr** [comment]
It looks like there was no update here, so I've resolved it myself. Thanks for the attempt.

**Comment by js-kyle** [comment]
@worr Sorry - this fell off my radar. Thanks heaps for your time in picking the issue up, and the library

**Pull request closed without merging**
