### PR TITLE
Added install step for devs new to js/npm

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by worr** [comment]
There are some extraneous changes in here

**Comment by amilajack** [comment]
@worr which changes should I remove?

**Comment by worr** [comment]
I don't agree with modifying the other two headers? Badges have nothing to do with problems with the removed interface to `imdb`. Also not sure why you made the `problems` header a second level header.

**Comment by amilajack** [comment]
Thanks for letting me know. Reverted those changes

**Comment by amilajack** [comment]
I also think it would be a good idea to migrate the docs to ES6 now. Would a PR for that be welcome?

**Pull request merged**
